# See: https://registry.terraform.io/modules/TaitoUnited/databases/digitalocean

# NOTE: If you use the additional database privilege modules for managing
# roles and users, you need to define database provider for each database
# in terraform/database-privileges.tf and enable kubernetes_db_proxy_enabled
# in taito-config.sh

postgresqlClusters:
  - name: ${postgres_default_name}
    region: ${taito_provider_region}
    version: "11"
    size: db-s-1vcpu-1gb
    nodeCount: 1
    maintenanceDay: 1
    maintenanceHour: 23
    # Privileges: https://registry.terraform.io/modules/TaitoUnited/privileges/postgresql
    # WARNING: Names of roles and users are visible for all database users
    roles:
    users:

mysqlClusters:
  # - name: ${mysql_default_name}
  #   region: ${taito_provider_region}
  #   version: "8"
  #   size: db-s-1vcpu-1gb
  #   nodeCount: 1
  #   maintenanceDay: 1
  #   maintenanceHour: 23
  #   # Privileges: https://registry.terraform.io/modules/TaitoUnited/privileges/mysql
  #   roles:
  #   users:
