- hosts: postgresql:allinone
  become: yes
  become_user: root
  roles:
    - postgresql
  vars_prompt:
    - name: "pg_admin_password"
      prompt: "(New) PostgreSQL database admin password"
      unsafe: yes
      private: yes
      confirm: yes
