# See: https://registry.terraform.io/modules/TaitoUnited/admin/azurerm

permissions:
  # CHANGE: either set your personal User Principal Name here or give name
  # of a group that already exists (e.g. developers)
  - name: john.doe_mydomain.com#EXT#@johndoemydomain.onmicrosoft.com
    type: user # CHANGE: user or group
    roles:
      - name: Azure Kubernetes Service Cluster User Role
        scope: /subscriptions/${taito_provider_billing_account_id}/resourcegroups/${taito_zone}/providers/Microsoft.ContainerService/managedClusters/${kubernetes_name}
