# See: https://registry.terraform.io/modules/TaitoUnited/databases/azurerm

# NOTE: If you use the additional database privilege modules for managing
# roles and users, you need to define database provider for each database
# in terraform/database-privileges.tf and enable kubernetes_db_proxy_enabled
# in taito-config.sh

postgresqlClusters:
  - name: ${postgres_default_name}
    location: ${taito_provider_region}
    version: "11"
    skuName: GP_Gen5_2
    storageMb: 20
    autoGrowEnabled: true
    backupRetentionDays: 30
    geoRedundantBackupEnabled: true
    infrastructureEncryptionEnabled: false
    publicNetworkAccessEnabled: false
    sslEnforcementEnabled: true
    sslMinimalTlsVersionEnforced: TLS1_2
    # authorizedNetworks:
    #   - start: 127.127.127.10
    #     end: 127.127.127.20
    adminUsername: ${postgres_default_admin}
    # Privileges: https://registry.terraform.io/modules/TaitoUnited/privileges/postgresql
    # WARNING: Names of roles and users are visible for all database users
    roles:
    users:

mysqlClusters:
  - name: ${mysql_default_name}
    location: ${taito_provider_region}
    version: "8.0"
    skuName: GP_Gen5_2
    storageMb: 20
    autoGrowEnabled: true
    backupRetentionDays: 30
    geoRedundantBackupEnabled: true
    infrastructureEncryptionEnabled: false
    publicNetworkAccessEnabled: false
    sslEnforcementEnabled: true
    sslMinimalTlsVersionEnforced: TLS1_2
    # authorizedNetworks:
    #   - start: 127.127.127.10
    #     end: 127.127.127.20
    adminUsername: ${mysql_default_admin}
    # Privileges: https://registry.terraform.io/modules/TaitoUnited/privileges/mysql
    roles:
    users:
