# See: https://registry.terraform.io/modules/TaitoUnited/kubernetes/azurerm

permissions:
  adminGroupObjectIds:
    # CHANGE: either set your personal user object id here or give object id
    # of a group that already exists (e.g. object id of admins group)
    - 1234567a-123b-123c-123d-1e2345a6c7e8

  clusterRoles:
    # EXAMPLE: Grant global development rights for some users/groups
    # - name: taito-developer
    #   subjects:
    #     - group:3333333a-123b-123c-123d-1e2345a6c7e8

    # EXAMPLE: Grant global status viewer rights for some users/groups
    # - name: taito-status-viewer
    #   subjects:
    #     - user:2222222b-123b-123c-123d-1e2345a6c7e8

  namespaces:
    # EXAMPLE: Grant reading common secrets for some users/groups
    # - name: common
    #   clusterRoles:
    #     - name: taito-secret-viewer
    #       subjects:
    #         - group:5555555a-123b-123c-123d-1e2345a6c7e8

    # EXAMPLE: Grant database access through a db proxy for some users/groups
    # - name: db-proxy
    #   clusterRoles:
    #     - name: taito-proxyer
    #       subjects:
    #         - group:5555555a-123b-123c-123d-1e2345a6c7e8
