# See: https://registry.terraform.io/modules/TaitoUnited/kubernetes/azurerm

# NOTE: cicd-tester service account is not required on production clusters
# NOTE: On multi-tenant setup, replace the zone specific CI/CD service
# account with tenant specific CI/CD service accounts, and give each
# 'taito-deployer' permissions only to specific namespaces.

permissions:
  # NOTE: adminGroupObjectIds is required only if azureAdManaged has been enabled
  # adminGroupObjectIds: [ "1234567a-123b-123c-123d-1e2345a6c7e8" ]
  clusterRoles:
    # EXAMPLE: Grant privileged deployment rights for the CI/CD service account
    # - name: taito-privileged-deployer
    #   subjects:
    #     - "2222222a-123b-123c-123d-1e2345a6c7e8"  # CI/CD service account object id

    # EXAMPLE: Grant global status viewer rights for all developers
    # NOTE: Not recommended on a multi-tenant setup
    # - name: taito-status-viewer
    #   subjects:
    #     - "3333333a-123b-123c-123d-1e2345a6c7e8"  # developer group object id

    # EXAMPLE: Grant global developer rights for all developers
    # NOTE: Not recommended on a production setup
    # - name: taito-developer
    #   subjects:
    #     - "3333333a-123b-123c-123d-1e2345a6c7e8"  # developer group object id

  namespaces:
    # EXAMPLE: Grant reading common secrets
    # - name: common
    #   clusterRoles:
    #     - name: taito-secret-viewer
    #       subjects:
    #         - "2222222a-123b-123c-123d-1e2345a6c7e8"  # CI/CD service account object id
    #         - "3222222a-123b-123c-123d-1e2345a6c7e8"  # CI/CD tester service account object id
    #         - "3333333a-123b-123c-123d-1e2345a6c7e8"  # developer group object id

    # EXAMPLE: Grant database access through a db proxy
    # - name: db-proxy
    #   clusterRoles:
    #     - name: taito-proxyer
    #       subjects:
    #         - "2222222a-123b-123c-123d-1e2345a6c7e8"  # CI/CD service account object id
    #         - "3222222a-123b-123c-123d-1e2345a6c7e8"  # CI/CD tester service account object id
