# See: https://registry.terraform.io/modules/TaitoUnited/storage/azurerm

storageAccounts:
  - name: ${taito_state_bucket}
    purpose: zone state
    location: ${taito_provider_region}
    accountTier: Standard
    accessTier: Hot
    accountReplicationType: ZRS
    containerAccessType: private
    allowNestedItemsToBePublic: false

  # NOTE: taito_projects_bucket not required on a multi-tenant zone
  - name: ${taito_projects_bucket}
    purpose: projects state
    location: ${taito_provider_region}
    accountTier: Standard
    accessTier: Hot
    accountReplicationType: ZRS
    containerAccessType: private
    allowNestedItemsToBePublic: false

  - name: ${taito_backup_bucket}
    purpose: backup
    location: ${taito_provider_region}
    accountTier: Standard
    accessTier: Cool
    accountReplicationType: ZRS
    containerAccessType: private
    allowNestedItemsToBePublic: false

  # - name: ${taito_public_bucket}
  #   purpose: public static assets
  #   location: ${taito_provider_region}
  #   accountTier: Standard
  #   accessTier: Hot
  #   accountReplicationType: ZRS
  #   containerAccessType: blob
  #   allowNestedItemsToBePublic: true
  #   cors:
  #     - origin: ["*"]
