# See: https://registry.terraform.io/modules/TaitoUnited/admin/aws

roles:
  - name: cicd
    policies: [ "serverless.deploy", "cicd.secrets.read" ]
    services: [ "ec2.amazonaws.com" ]
  - name: logging
    policies: [ "logging.write" ]
    services: [ "ec2.amazonaws.com" ]

groups:
  - name: developers
    path: /
    policies: [ "kubernetes.connect", "logging.read" ]
    assumeRoles:
      - "arn:aws:iam::56789012345:role/developer"

users:
  # CHANGE: Add developers here
  - name: john.doe
    groups: [ "developers" ]
