# See: https://registry.terraform.io/modules/TaitoUnited/storage/aws

storageBuckets:
  - name: ${taito_state_bucket}
    purpose: zone state
    acl: private
    versioningEnabled: true
    versioningRetainDays: 90

  - name: ${taito_projects_bucket}
    purpose: projects state
    acl: private
    versioningEnabled: true
    versioningRetainDays: 90

  - name: ${taito_backup_bucket}
    purpose: backup
    acl: private
    versioningEnabled: false

  - name: ${taito_public_bucket}
    purpose: public static assets
    acl: public-read
    versioningEnabled: true
    versioningRetainDays: 60
    corsRules:
      - allowedOrigins: ["*"]
