settings:
  # TODO: support for authorized network CIDRs on Kubernetes setup
  authorizedNetworks:
    - cidr: 0.0.0.0/0 # Your public IP address range here

  # developers:
  #   - arn: arn:aws:iam::${taito_provider_org_id}:user/john-doe

  kubernetes:
    name: ${kubernetes_name}
    context: ${taito_zone}
    nodePools:
      - name: pool-1
        machineType: n1-standard-1
        diskSizeGb: 100
        minNodeCount: 2
        maxNodeCount: 2
    nginxIngressControllers:
      - class: nginx
        replicas: 2

  postgresClusters:
    - name: ${postgres_default_name}
      tier: db.t3.medium
      size: 20
      adminUsername: ${taito_zone_short}
      # TODO: support for db users
      # users:
      #   - username: john.doe
      #     read:
      #       - my-project-prod
      #     write:
      #       - another-project-prod

  mysqlClusters:
    - name: ${mysql_default_name}
      tier: db.t3.medium
      size: 20
      adminUsername: ${taito_zone_short}
      # TODO: support for db users
      # users:
      #   - username: john.doe
      #     read:
      #       - my-project-prod
      #     write:
      #       - another-project-prod
