dependencies:
  - role: apt
    repositories:
      - "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    key_urls:
      - "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    packages:
      - python3-psycopg2
      - "postgresql-client-{{ pg.version | default('15') }}"
      - mariadb-client
      - python3-mysqldb
