- name: Make sure sudo is installed
  apt:
    pkg: sudo

- name: Allow sudo group to run sudo without password
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%sudo"
    line: "%sudo   ALL=(ALL:ALL) NOPASSWD:ALL"
    state: present
    validate: "visudo -cf %s"

- name: Allow specific commands to be run with sudo and without password by specific users
  lineinfile:
    dest: /etc/sudoers
    line: "%{{ item.value.username }}   ALL=(ALL) NOPASSWD: {{ item.value.command }}"
    state: present
    validate: "visudo -cf %s"
  with_dict: "{{ allow_sudo_commands | default({}) }}"

- name: Disallow root ssh access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify:
    - Restart sshd

- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify:
    - Restart sshd

- name: Lock root password
  user:
    name: root
    password_lock: yes

- name: SSH client alive interval 5 minutes
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^ClientAliveInterval"
    line: "ClientAliveInterval 300"
    state: present
  notify:
    - Restart sshd

- name: SSH client alive count max 0
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^ClientAliveCountMax"
    line: "ClientAliveCountMax 0"
    state: present
  notify:
    - Restart sshd
