# See: https://registry.terraform.io/modules/TaitoUnited/admin/google

# - NOTE: cicd-tester service account is not required on production clusters
# - NOTE: On multi-tenant setup, replace the zone specific cloudbuild service
# account with tenant specific cloudbuild service accounts.
# - TIP: You can create custom roles at the project or organization level, see:
# https://cloud.google.com/iam/docs/creating-custom-roles
# - TIP: You can create groups for your domain, see:
# https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#google-groups-for-gke

permissions:
  - id: "serviceAccount:${taito_provider_taito_zone_id}@cloudbuild.gserviceaccount.com"
    roles: ["roles/container.clusterViewer"]

serviceAccounts:
  - id: "cicd-tester"
    roles: ["roles/container.clusterViewer"]
    description: >
      Service account for running tests on CI/CD. Connects to database
      through a database proxy running on Kubernetes cluster.

apis:
  - id: "cloudbuild.googleapis.com" # NOTE: Not required for multi-tenant
  - id: "cloudfunctions.googleapis.com"
  - id: "cloudkms.googleapis.com"
  - id: "cloudscheduler.googleapis.com"
  - id: "compute.googleapis.com"
  - id: "container.googleapis.com"
  - id: "containerregistry.googleapis.com" # NOTE: Not required for multi-tenant
  - id: "monitoring.googleapis.com"
  - id: "pubsub.googleapis.com"
  - id: "secretmanager.googleapis.com"
  - id: "servicenetworking.googleapis.com"
  - id: "sql-component.googleapis.com"
  - id: "sqladmin.googleapis.com"
  # NOTE: You might also want to enable these
  # - id: "binaryauthorization.googleapis.com"
  # - id: "dns.googleapis.com"
  # - id: "containeranalysis.googleapis.com"
