# See: https://registry.terraform.io/modules/TaitoUnited/admin/google

members:
# TIP: You can create custom roles at the project or organization level
# https://cloud.google.com/iam/docs/creating-custom-roles
# - id: "group:developers@mydomain.com"
#   roles: [ "custom/developer" ]

serviceAccounts:
  # NOTE: CI/CD tester service account is not required on production clusters
  - id: "cicd-tester"
    roles: [ "roles/container.clusterViewer" ]
    description: >
      Service account for running tests on CI/CD. Connects to database
      through a database proxy running on Kubernetes cluster.

apis:
  - id: "cloudbuild.googleapis.com"
  - id: "cloudkms.googleapis.com"
  - id: "compute.googleapis.com"
  - id: "container.googleapis.com"
  - id: "containerregistry.googleapis.com"
  - id: "monitoring.googleapis.com"
  - id: "pubsub.googleapis.com"
  - id: "servicenetworking.googleapis.com"
  - id: "sql-component.googleapis.com"
  - id: "sqladmin.googleapis.com"
