# See: https://registry.terraform.io/modules/TaitoUnited/kubernetes/google

permissions:
  clusterRoles:
    # Grant developer access to ALL namespaces
    # NOTE: Not recommended on production clusters
    - name: taito-developer
      subjects:
        - "GCP_PROJECT_NUMBER@cloudbuild.gserviceaccount.com"
  namespaces:
    # Grant database access through a db proxy
    - name: db-proxy
      clusterRoles:
        - name: taito-pod-portforwarder
          subjects:
            # NOTE: CI/CD tester account is not required on production clusters
            - "user:cicd-tester@${taito_zone}.iam.gserviceaccount.com"

# For Kubernetes setting descriptions, see
# https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/
kubernetes:
  name: ${kubernetes_name}
  context: ${taito_zone}
  releaseChannel: STABLE
  maintenanceStartTime: 02:00
  registryProjectId:
  authenticatorSecurityGroup: GKE_SECURITY_GROUP
  rbacSecurityGroup:
  clusterFirewallRulesEnabled: false
  masterPrivateEndpointEnabled: false
  masterGlobalAccessEnabled: true
  privateNodesEnabled: true
  shieldedNodesEnabled: true
  networkPolicyEnabled: false
  dbEncryptionEnabled: false
  podSecurityPolicyEnabled: false
  verticalPodAutoscalingEnabled: true
  dnsCacheEnabled: true
  pdCsiDriverEnabled: true
  resourceConsumptionExportEnabled: false
  resourceConsumptionExportDatasetId:
  networkEgressExportEnabled: false
  binaryAuthorizationEnabled: false
  intranodeVisibilityEnabled: false
  configConnectorEnabled: false
  region: ${taito_provider_region}
  regional: false
  zones: [ "${taito_provider_zone}" ]
  masterAuthorizedNetworks:
    - 0.0.0.0/0

  # Node pools
  nodePools:
    - name: pool-1
      machineType: n1-standard-1
      acceleratorType:
      acceleratorCount: 0
      secureBootEnabled: true
      diskSizeGb: 100
      locations: # Leave empty or specify zones, example: europe-west1-b,europe-west1-c
      # NOTE: On Google Cloud total number of nodes = node_count * num_of_zones
      minNodeCount: 1
      maxNodeCount: 1

  # Ingress controllers
  nginxIngressControllers:
    - class: nginx
      replicas: 3
      metricsEnabled: true
      # MaxMind license key for GeoIP2:
      # https://support.maxmind.com/account-faq/license-keys/how-do-i-generate-a-license-key/
      maxmindLicenseKey:
      # See https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
      # See https://kubernetes.github.io/ingress-nginx/deploy/hardening-guide/
      configMap:
        keep-alive: 10
        hide-headers: Server, X-Powered-By
        ssl-ciphers: EECDH+AESGCM:EDH+AESGCM
        enable-ocsp: true
        hsts-preload: true
        ssl-session-tickets: false
        enable-modsecurity: true
        enable-owasp-modsecurity-crs: true
        use-geoip: false
        use-geoip2: true
        enable-real-ip: false
        enable-opentracing: false
        whitelist-source-range:
        # Block malicious IPs. See https://www.projecthoneypot.org/list_of_ips.php
        block-cidrs:
        block-user-agents:
        block-referers:
      # Map TCP/UDP connections to services
      tcpServices:
      udpServices:

  # Certificate managers
  certManager:
    enabled: true

  # Platforms
  istio:
    enabled: false
  knative:
    enabled: false

  # Logging, monitoring, and tracing
  falco:
    enabled: false
  jaeger:
    enabled: false
  sentry:
    enabled: false

  # CI/CD
  jenkinsx:
    enabled: false
