# See: https://registry.terraform.io/modules/TaitoUnited/monitoring/google

alerts:
  - name: kubernetes-container-errors
    type: log
    channels: [ "monitoring" ]
    rule: >
      resource.type="k8s_container"
      severity>=ERROR
  - name: nginx-ingress-response-time
    type: log
    channels: [ "monitoring" ]
    rule: >
      resource.type="k8s_container"
      resource.labels.namespace_name="nginx-ingress"
      jsonPayload.responseTimeS>=3
