# See: https://registry.terraform.io/modules/TaitoUnited/monitoring/google

alerts:
  - name: container-errors
    type: log
    channels: [ "monitoring" ]
    rule: >
      resource.type="k8s_container"
      severity>=ERROR
  - name: ingress-response-time
    type: log
    channels: [ "monitoring" ]
    rule: >
      resource.type="k8s_container"
      resource.labels.namespace_name="ingress-nginx"
      jsonPayload.responseTimeS>=3
