# See: https://registry.terraform.io/modules/TaitoUnited/monitoring/google

# NOTE: Monitoring module is disabled by default. You can enable it with
# these steps:
# - Go to monitoring page on Google Cloud web console. This will create you a
#   workspace for monitoring.
# - Enable the module in terraform/monitoring.tf
# - Apply changes with 'taito zone apply'

alerts:
  - name: ingress-response-time
    type: log
    channels: [ "monitoring" ]
    rule: >
      resource.type = "k8s_container"
      resource.labels.namespace_name = "ingress-nginx"
      httpRequest.latency >= "3.0s"

  - name: ingress-response-status
    type: log
    channels: [ "monitoring" ]
    rule: >
      resource.type = "k8s_container"
      resource.labels.namespace_name = "ingress-nginx"
      jsonPayload.status >= 500

  - name: container-errors
    type: log
    channels: [ "monitoring" ]
    rule: >
      resource.type = "k8s_container"
      severity >= ERROR
