# See: https://registry.terraform.io/modules/TaitoUnited/network/google

network:
  name: ${taito_zone}
  region: ${taito_provider_region}
  natEnabled: true # NAT is required for private Kubernetes or virtual machines
  privateGoogleServicesEnabled: true
  flowLoggingEnabled: false
  vpcSharingEnabled: false
  sharedVpcServiceProjects: []
