- name: Make sure that ufw is installed
  apt:
    pkg: ufw

- name: Allow ssh through firewall
  ufw:
    rule: allow
    to_port: "22"
    proto: tcp
    src: '{{ item }}'
  loop: "{{ lookup('env','taito_ssh_authorized_networks').split(' ') }}"
  notify:
    - Reload ufw

- name: Deny all IPv6 to port 22 just in case it was allowed at some point
  ufw:
    rule: deny
    proto: tcp
    port: "22"
    to_ip: "::"
    insert: 0
    insert_relative_to: first-ipv6

- name: Make deny the default firewall policy
  ufw:
    policy: deny
    direction: incoming
  notify:
    - Reload ufw

- name: Enable firewall (ufw)
  ufw:
    state: enabled
  notify:
    - Reload ufw
