- name: Make sure that ufw is installed
  apt:
    pkg: ufw

- name: Make deny the default firewall policy
  ufw:
    policy: deny
    direction: incoming
  notify:
    - Reload ufw

- name: Enable firewall (ufw)
  ufw:
    state: enabled
  notify:
    - Reload ufw
