dependencies:
  - role: ufw
  - role: apt
    packages:
      - acl
      - python3-psycopg2
      - "postgresql-{{ pg.version | default('13') }}"
      # - "postgresql-contrib-{{ pg.version | default('13') }}"
      - "postgresql-client-{{ pg.version | default('13') }}"
